---
- hosts: deploymentservers
  become: true
  become_method: su
  remote_user: bbills
  tasks:
  - name: Ensure perl is the latest version
    yum: pkg=perl state=latest
  - name: Copy VMwareTools to client
    copy: src=/tmp/VMwareTools-10.1.6-5214329.tar.gz dest=/tmp/VMwareTools-10.1.6-5214329.tar.gz
  - name: Unarchive VMwareTools
    unarchive: src=/tmp/VMwareTools-10.1.6-5214329.tar.gz dest=/tmp
  - name: Launch VMwareTools installation
    command: /tmp/vmware-tools-distrib/vmware-install.pl -d
  - name: Clean extracted folder
    file: path={{item}} state=absent
    with_items:
    - /tmp/vmware-tools-distrib
  - name: Clean archive file
    file: path=/tmp/VMwareTools-10.1.6-5214329.tar.gz state=absent
